[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
markers =
    unit: small, fast tests that mock database/external services
    integration: tests that use Testcontainers and actual database
